[package]
name = "eq-client-render"
description = "Bevy renderer for native EverQuest clients"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bevy.workspace = true
eq-client-assets.workspace = true

[lints]
workspace = true
