[package]
name = "eq-client"
description = "Native top-down EverQuest client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
clap.workspace = true
eq-client-assets.workspace = true
eq-client-render.workspace = true

[lints]
workspace = true
