[package]
name = "eq-client-core"
description = "Engine-independent world state for native EverQuest clients"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
parry3d.workspace = true
eq-client-axes.workspace = true
glam.workspace = true
eq-network-game.workspace = true

[lints]
workspace = true
